name: Run Gradle on PRs
on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
    - '**'
    - '!branch-*.*'
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    
    - name: Execute Gradle build
      run: ./gradlew build
